name: Test Python

on:
  workflow_call:
    inputs:
      python-version:
        description: 'The version of Python to use'
        type: string
        required: true
      pkg-name:
        description: 'The name of the package (for coverage)'
        type: string
        required: true
      tests-path:
        description: 'Path to point to for tests'
        required: false
        type: string
        default: 'tests'

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test t-wave
        if: always()
        uses: ./test-python
        with:
          pkg-name: ${{ inputs.pkg-name }}
          path: ${{ inputs.tests-path }}
          python-version: ${{ inputs.python-version }}
