name: 'Python code check'
description: 'Run Python code quality tools against code'

inputs:
  python-version:
    description: The version of Python to use. For 3.10, remember to enclose it in quotes so it is cast as a string!
    required: true
  path:
    description: 'Path to point to for checks'
    required: false
    default: '.'

# TODO: Add options to enable/disable checks for specific packages? See if I can check whether a package is installed or not before attempting to run it?

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4

    - name: Build Python
      uses: eshwen/adrenaline/builder@v0.4.0
      with:
        python-version: ${{ inputs.python-version }}
        install-dev-deps: true

    - id: ruff
      name: Ruff lint
      if: always()
      shell: bash
      run: poetry run ruff ${{ inputs.path }}

    - id: ruff_format
      name: Ruff format
      if: always()
      shell: bash
      run: poetry run ruff format ${{ inputs.path }} --diff

    - id: mypy
      if: always()
      shell: bash
      run: poetry run mypy ${{ inputs.path }}
