name: 'Test Python'
description: 'Test our Python code'

inputs:
  python-version-file:
    description: The file containing the Python version of your project. Defaults to pyproject.toml.
    required: false
    default: pyproject.toml
  uv-version:
    description: The version of uv to install e.g., `0.5.0` Defaults to the version in pyproject.toml or 'latest'.
    default: ""
  pkg-name:
    description: 'The name of the package (for coverage)'
    required: true
  tests-path:
    description: 'Path to point to for pytest'
    required: false
    default: 'tests'
  args:
    description: 'Extra arguments to pass to pytest, e.g., `--cov-report xml`'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Build Project
      uses: eshwen/adrenaline/builder@v0.8.0
      with:
        python-version: ${{ inputs.python-version }}
        install-dev-deps: true
        uv-version: ${{ inputs.uv-version }}

    - name: Install test failure annotator
      shell: bash
      run: |
        uv pip install pytest-github-actions-annotate-failures

    - name: Test Python
      shell: bash
      run: uv run pytest ${{ inputs.args }} --cov ${{ inputs.pkg-name }} ${{ inputs.tests-path }}
      if: ${{ always() }}
