name: Build API docs

on:
  workflow_call:
    inputs:
      python-version:
        description: 'The version of Python to use. For 3.10, remember to enclose it in quotes so it's cast as a string!'
        type: string
        required: true
      changelog:
        description: 'The changelog file to use (optional). Requires the `git-changelog` package to be installed'
        required: false
        type: string
        default: ''

concurrency:
  group: docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: eshwen/adrenaline/builder@v0.2.3
        with:
          python-version: ${{ inputs.python-version }}
          install-dev-deps: true

      - name: Build Changelog
        run: |
          git fetch --unshallow
          poetry run git-changelog -p github -o ${{ inputs.changelog }}
        if: ${{ inputs.changelog != inputs.changelog.default }}

      - name: Build and publish
        run: |
          poetry run mkdocs gh-deploy
