name: Check Quality of Python (uv)

on:
  workflow_call:
    inputs:
      python-version-file:
        description: The file containing the Python version of your project. Defaults to pyproject.toml.
        required: false
        type: string
        default: pyproject.toml
      uv-version:
        description: The version of uv to install e.g., `0.5.0` Defaults to the version in pyproject.toml or 'latest'.
        type: string
        required: false
        default: ""
      path:
        description: 'Path to point to for checks'
        required: false
        type: string
        default: '.'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check code quality
        if: always()
        uses: eshwen/adrenaline/uv/check-python@v0.8.0
        with:
          python-version-file: ${{ inputs.python-version-file }}
          uv-version: ${{ inputs.uv-version }}
          path: ${{ inputs.path }}
